services:
  sas-app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_ACCESS_KEY=${VITE_ACCESS_KEY}
    container_name: sas-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    env_file:
      - ../.env
